### PR TITLE
Merge from upstream 

### PR DESCRIPTION
**Pull request by xantoz**
Because license incompatibilities makes this the only feasible merge.

### CODE REVIEW

**Comment by pigoz** [comment]
lol

**Comment by wm4** [comment]
This is the worst PR I've ever seen.

**Comment by xantoz** [comment]
AGPL is the worst license I've seen.

**Comment by wm4** [comment]
Too many bad commits.

I also clarified the license issue: 0dd76f1261b1a6606

Now you don't need to bother with this annoying merging stuff anymore.

**Comment by xantoz** [comment]
Thanks. This helped me make up my mind about you and this fork.

**Comment by wm4** [comment]
I see. Go fuck yourself too.

**Pull request closed without merging**
